api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    path('products/', views.product_list),
    path('order-id/<str:id>', views.order_details),
]

urlpatterns = format_suffix_patterns(urlpatterns)

project_name/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views
from shop import views as viewsshop

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', viewsshop.crud, name = "home"),
    path('category/<str:cat>', viewsshop.showcategory, name = "showcategory"),
    path('brands/<str:comp>', viewsshop.showcompany, name = "showcompany"),
    path('product/<str:product_id>', viewsshop.showproduct, name = "showproduct"),
    path('signup/', views.signup, name = "signup"),
    path('logout/', views.logout_request, name = "logout"),
    path('login/', views.login_request, name = "login"),
    path('account/', views.account, name = "account"),
    path('order/', viewsshop.order, name = "order"),
    path('shop/', include('shop.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.crud, name = "CrudOps")
]

shopping_mart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views
from shop import views as viewsshop

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', viewsshop.crud, name = "home"),
    path('category/<str:cat>', viewsshop.showcategory, name = "showcategory"),
    path('brands/<str:comp>', viewsshop.showcompany, name = "showcompany"),
    path('product/<str:product_id>', viewsshop.showproduct, name = "showproduct"),
    path('signup/', views.signup, name = "signup"),
    path('logout/', views.logout_request, name = "logout"),
    path('login/', views.login_request, name = "login"),
    path('account/', views.account, name = "account"),
    path('order/', viewsshop.order, name = "order"),
    path('api/', include('api.urls')),
    path('shop/', include('shop.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):

    id = models.AutoField(primary_key = True)
    name = models.CharField(max_length = 200)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.name


class Company(models.Model):

    id = models.AutoField(primary_key = True)
    name = models.CharField(max_length = 200)
    created_at = models.DateField(auto_now_add=True)
    logo = models.ImageField(upload_to='shop/images/company', blank= True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.name

class Product(models.Model):

    id = models.AutoField(primary_key = True)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=1000)
    company = models.ForeignKey(Company, on_delete = models.CASCADE, blank = True)
    price = models.IntegerField()
    discount = models.IntegerField()
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    product_image = models.ImageField(upload_to='shop/images/product')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    
    order_id = models.CharField(max_length=200)
    products_id = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete = models.CASCADE, blank = True)
    total = models.IntegerField()
    discount = models.IntegerField()
    status = models.CharField(max_length=100, blank=True, null=True)
    tax = models.IntegerField()
    price = models.IntegerField()
    address = models.CharField(max_length=1000)
    pincode = models.IntegerField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.order_id

shop/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.models import User
from .forms_order import OrderForm

from .models import Product, Category, Company, Order
# Create your views here.

def crud(request):

    products = Product.objects.all()
    categories = Category.objects.all()
    companies = Company.objects.all()
    
    params = {'products': products, 'categories' : categories, 'companies' : companies}

    return render(request, 'shop/index.html', params)

def showcategory(request, cat):

    categories = Category.objects.all()
    companies = Company.objects.all()

    cats = Category.objects.get(name=cat)

    products = Product.objects.filter(category=cats).values()

    params = {'products' : products, 'category' : cat, 'categories' : categories, 'companies' : companies}

    return render(request, 'shop/category.html', params)


def showcompany(request, comp):

    categories = Category.objects.all()
    companies = Company.objects.all()

    comps = Company.objects.get(name=comp)

    products = Product.objects.filter(company=comps).values()

    params = {'products' : products, 'category' : comp, 'categories' : categories, 'companies' : companies}

    return render(request, 'shop/category.html', params)

def showproduct(request, product_id):

    product = Product.objects.get(id=product_id)
    related = Product.objects.exclude(id=product_id).values

    params = {'product' : product, 'related' : related}

    return render(request, 'shop/product.html', params)

def order(request):
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid(): # All validation rules pass
            order = form.save(commit=False)
            order.user = request.user
            order.status = 'PLACED'
            order.order_id = "OrderId" + str(form.cleaned_data.get('order_id'))
            order.save()
            params = {'submitted' : '1'}
            return render(request, 'shop/order.html', params)    
    else:
        form = OrderForm()

    return render(request, 'shop/order.html', {
        'form': form, 'submitted' : '0',
    })

templates/shop/category.html
{% extends "base.html" %} 
{% block title %}{{category}} | ShoppingMart{% endblock %} 
{% block content %} 

<div style="background: #f7f8fa; padding: 5px 0px;">

    <div class="container">
        Home / {{category}}
    </div>

</div>

<div style="max-width: 1150px; margin: 0px auto; display: flex; flex-direction: row;">
    <div id="left-tab" style="display: flex; flex-direction: column; width: 200px;">
        
        <div style="width: 200px;">
            <div style="padding: 20px 30px; border-bottom: 1px solid #fafafa;">
                Categories
            </div>
            <div>
                {% for cat in categories %}
                <a href="/category/{{cat.name}}"><div>{{cat.name}}</div></a>
                {% endfor %}
            </div>
        </div>

        <div style="width: 200px;">
            <div style="padding: 20px 30px; border-bottom: 1px solid #fafafa;">
                Brands
            </div>
            <div>
                {% for comp in companies %}
                <a href="/brands/{{comp.name}}"><div>{{comp.name}}</div></a>
                {% endfor %}
            </div>
        </div>
        
    </div>
    <div id="right-tab" style="display: flex; flex-direction: column;">
        {{category}}

        <div>
            {% for prod in products %}
            
            <a href="/product/{{prod.id}}">
            <div class="product-c">
                <img src="/media/{{prod.product_image}}" />
                <div class="product-company">{{prod.company.name}}</div>
                <div class="product-details">
                    <div class="product-rating">
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        </div>
                    <div class="product-name">{{prod.name}}</div>
                    <div class="product-price"><span class="fa fa-inr"></span> {{prod.price}}</div>
                </div>
            </div>
        </a>
        
            {% endfor %}
        
        </div>


    </div>

</div>


{% endblock %} 

templates/shop/index.html
{% extends "base.html" %} 
{% block title %}Shopping Mart{% endblock %} 
{% block content %} 

{% load static %}
<img class="cover-img" src="{% static 'shop/cover1.png'%}" />

<div id="category-container">

    {% for cat in categories %}
    <a href="/category/{{cat.name}}"><div class="category-c">{{cat.name}}</div></a>
    {% endfor %}
</div>

<div class="center margin-gap">
    <div class="heading">BEST SELLER</div>
    <div class="sub-heading">TOP PRODUCTS OF THE WEEK</div>
</div>

<div class="center margin-gap">

    {% for prod in products %}

    <a href="/product/{{prod.id}}">
    <div class="product-c">
        <img src="/media/{{prod.product_image}}" />
        <div class="product-company">{{prod.company.name}}</div>
        <div class="product-details">
            <div class="product-rating">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                </div>
            <div class="product-name">{{prod.name}}</div>
            <div class="product-price"><span class="fa fa-inr"></span> {{prod.price}}</div>
        </div>
    </div>
</a>
    {% endfor %}

    <div class="center margin-gap">
        <div class="heading">BRANDS</div>
        <div class="sub-heading">TOP BRANDS OF THE WEEK</div>
    </div>

    <div id="category-container">

        {% for com in companies %}
        <div class="company-c"><img src="/media/{{com.logo}}" /></div>
        {% endfor %}

        {% for u in users %}
        <div>{{u.email}}</div>
        {% endfor %}
    </div>


</div>


{% endblock %} 

templates/shop/order.html
{% extends "base.html" %} 
{% block title %}Order | ShoppingMart{% endblock %} 
{% block content %} 

<script>

    console.log(JSON.parse(localStorage.getItem("products")));

    function changeQty(id, c) {

        product = JSON.parse(window.localStorage.getItem('products'));

        for(var i = 0; i < product.length; i++) {
            if(id == product[i].id) {
                if(c == 0 && product[i].qty > 0) { 
                    product[i].qty = "" + (parseInt(product[i].qty, 10) - 1);
                } else if(c == 1)
                product[i].qty = "" + (parseInt(product[i].qty, 10) + 1);
            }
        }

        localStorage.setItem('products', JSON.stringify(product));
        loadCart();

    }

function loadCart() {

    var submitted = "{{submitted}}";

    if(submitted == 0) {
        
    product = JSON.parse(window.localStorage.getItem('products'));

    if(product.length > 0) {
    
    var x = '<div style="font-weight: bold; padding: 10px; border-bottom: 1px solid #eee;">Your Cart</div><div>';
    var total = 0, prodsid = '';
    for(var i = 0; i < product.length; i++) {
    x += '<div class="display-row div-products"><div class="display-column width-300"><div>' + product[i].name + '</div><div class="font-14" style="margin-top: 4px;">QTY  <span class="qty" onclick="changeQty(' + product[i].id + ', 0)">-</span> ' + product[i].qty + ' <span class="qty" onclick="changeQty(' + product[i].id + ', 1)">+</span></div></div><div class="width-100"><i class="fa fa-inr"></i>&nbsp;' + (product[i].qty * product[i].price) + '</div></div>';
    total += product[i].qty * product[i].price;
    if(i == (product.length - 1))
    prodsid += product[i].id;
    else prodsid += product[i].id + '@';
    }

    x += '</div><div class="display-row div-total"><div class="width-300">Total Amount</div><div class="width-100"><i class="fa fa-inr"></i>&nbsp;' + total + '</div></div>';

    document.getElementById('id_total').value = total;
    document.getElementById('id_products_id').value = prodsid;
    document.getElementById('id_order_id').value = Math.floor(Date.now() / 1000);
    document.getElementById("cart-c").innerHTML = x;

    } else {
        document.getElementById("cc").innerHTML = "You haven't added anything to your cart! Check products here&nbsp;<a href='/'>here</a>.";
    }
    } else {
        localStorage.clear();
        document.getElementById("cc").innerHTML = "You have successfully placed your order! Check account for details&nbsp;<a href='/account'>here</a>.";
    }
}


</script>

<style>

    .display-row {
        display: flex; flex-direction: row;
    }
    
    .display-column {
        display: flex; flex-direction: column;
    }

    .div-total {
        padding: 10px;
    }

    .div-products {
        padding: 10px; border-bottom: 1px solid #fafafa;
    }

    .width-300 {
        width: 300px;
    }

    .width-100 {
        width: 100px; text-align: right;
    }

    .font-14 {
        font-size: 14px;
    }

    .qty {
        padding: 2px 8px; cursor: pointer; background: #f7f8fa;
    }


</style>

<div style="background: #f7f8fa; padding: 5px 0px;">

<div id="cc" style="max-width: 1150px; margin: 20px auto; display: flex; flex-direction: row;">
    <div id="left-tab" style="display: flex; flex-direction: column; width: 500px;">
        
        <form method="post" novalidate>
            {% csrf_token %}
            <div style="background-color: white; padding: 10px; margin-bottom: 10px;">
            <p>{{form.address.label_tag}} {{form.address}} {{form.address.errors}}</p>
            <p>{{form.pincode.label_tag}} {{form.pincode}} {{form.pincode.errors}}</p>
            <p style="display: none;">
                <input type="number" name="total" value="0" maxlength="1000" required="" id="id_total">
                <input type="text" name="products_id" value="" maxlength="1000" required="" id="id_products_id">
                <input type="number" name="discount" value="0" maxlength="1000" required="" id="id_discount">
                <input type="number" name="tax" value="0" maxlength="1000" required="" id="id_tax">
                <input type="number" name="order_id" value="0" maxlength="1000" required="" id="id_order_id">
                <input type="number" name="price" value="0" maxlength="1000" required="" id="id_price">
            </p>
            </div>
            <button style="background: #007bff; color: white; border: 0; padding: 10px 15px; border-radius: 5px; outline: 0;" type="submit">Place Order</button>
        </form>
        
    </div>
    <div class="display-column" id="right-tab" style="background-color: white; padding: 10px; width: 400px; margin-left: 30px;">

        <div id="cart-c">
            
       
        </div>


    </div>

</div>
</div>


<script>
if(localStorage.getItem('products') === null) {
    document.getElementById("cc").innerHTML = "You haven't added anything to your cart! Check products here&nbsp;<a href='/'>here</a>.";
} else {
loadCart();
}

</script>

{% endblock %} 

templates/shop/product.html
{% extends "base.html" %} 
{% block title %}{{product.name}} | ShoppingMart{% endblock %} 
{% block content %} 

<script>

    function addProduct() {
        const prod = {
            id: "{{product.id}}",
            name: "{{product.name}}",
            price: "{{product.price}}",
            qty: "1"
        }

        var prods = [];
        var exists = 0;

        if(localStorage.getItem('products') === null) {
            prods[0] = prod;
        } else {
            prods = JSON.parse(localStorage.getItem('products'));
            for(var i = 0; i < prods.length; i++) {
                if(prods[i].id == prod.id) {
                    exists = 1;
                    if(prods[i].qty == 0)
                    prods[i].qty = 1;
                }  
            }
            if(exists == 0)
            prods[prods.length] = prod; 
        }

        localStorage.setItem('products', JSON.stringify(prods));
        window.location = '/order/';

    }


</script>

<style>
    #add-cart {
        background: #2879fe; cursor: pointer; display: flex; color: white; border-radius: 5px; padding: 10px 0px; justify-content: center; margin-right: 10px; width: 40%;
    }

    #add-cart:hover {
        background: #f7f8fa; cursor: pointer; display: flex; color: #2879fe; border-radius: 5px; padding: 10px 0px; justify-content: center; margin-right: 10px; width: 40%;  
    }


</style>

<div style="background: #f7f8fa; padding: 5px 0px;">

    <div class="container">
        Home / {{product.name}}
    </div>

</div>

<div style="max-width: 1150px; margin: 20px auto; display: flex; flex-direction: row;">
    <div id="left-tab" style="display: flex; flex-direction: column; width: 500px;">
        
       <img style="width: 100%;" src="/media/{{product.product_image}}" />
        
    </div>
    <div id="right-tab" style="display: flex; width: 600px; flex-direction: column; margin-left: 30px;">
      
        <div>SKU : {{product.id}}</div>
        <div style="font-size: 30px;">{{product.name}}</div>
        <div style="font-size: 42px; color: #2879fe;">{{product.price}}</div>
        <div>Tax Included</div>

        <div style="display: flex; flex-direction: row; margin: 10px 0px;">
        <div id="add-cart" onclick="addProduct();">
            Add to Cart
        </div>
        </div>

        <img style="margin: 20px 0px;" src="/static/shop/payment.png" />

        <div>
            Category : {{product.category.name}} <br>
            Brand : {{product.company.name}}<br><br>
            <b>DESCRIPTION</b><br><br>
            {{product.description}}
        </div>


    </div>

</div>

<div style="background: #f7f8fa; padding: 5px 0px; text-align: center;">

    <img src="/static/shop/social.png" />

</div>

<div style="max-width: 1150px; margin: 20px auto;">

    <b>RELATED PRODUCTS</b>

    <div style="margin-top: 20px;">
        {% for prod in related %}
        
        <a href="/product/{{prod.id}}">
        <div class="product-c">
            <img src="/media/{{prod.product_image}}" />
            <div class="product-company">{{prod.company.name}}</div>
            <div class="product-details">
                <div class="product-rating">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    </div>
                <div class="product-name">{{prod.name}}</div>
                <div class="product-price"><span class="fa fa-inr"></span> {{prod.price}}</div>
            </div>
        </div>
    </a>
    
        {% endfor %}
    
    </div>



</div>


{% endblock %} 